//
// Created by chevalier on 08/08/18.
//

//---------------------------------------------------------------------------------------
// J.M. Muller sequence

#include <ostream>
#include <shaman.h>

/*
 * J.M. Muller sequence
 *
 * The UNSTABLE DIVISION(S) are generated by divisions where the denominator has no significant value or is a mathematical zero.
 * Such operations make the computed trajectory turn off the exact trajectory and then, the estimation of accuracy is not possible any more.
 * Even using the double precision, the computer cannot give any significant result after the iteration Sdouble 15.
 *
 * http://www-pequan.lip6.fr/cadna/Examples_Dir/ex4.php
 */
void muller()
{
  std::cout << "Muller sequence." << '\n'
            << "The unstable division make us unable to track the precision past them."
            << std::endl;

  Sdouble a = 5.5;
  Sdouble b = 61.0/11.0;

  for (int i = 3; i <= 25; i++)
  {
    Sdouble c = b;
    b = 111.0 - 1130.0/b + 3000.0/(a*b);
    a = c;
    std::cout << "U(" << i << ") = " << b << std::endl;
  }

  std::cout << "The true limit is 6." << std::endl;
  //displayError(a, 6);

  std::cout << std::endl;
}

int main() {
  muller();
  return EXIT_SUCCESS;
}