#!/bin/bash

# Réalise l'étude de convergence du calcul d'intégrale
./unitTest.exe 1.1 > cvPlot.dat

# Fait tourner le cacul d'intégral avec les fonctions de débuggage
./unitTest_debug.exe 1.1

# Produit une courbe représentant l'erreur en fonction du nombre de rectangles dans "cvPlot.pdf"
gnuplot cvPlot.gp
