#!/bin/bash

function synthese () {
    local TYPE="$1"
    for DIR in dd.${TYPE}.* ; do
        local NAME=$(echo ${DIR} | perl -pne "s/^dd.${TYPE}.//" | c++filt)
        local STATUS="FAIL"
        if [ -e "${DIR}/dd.pass" ]; then
            STATUS="PASS"
        fi
        local COUNT=$(ls -d "${DIR}/dd.run"* | wc -l)
        local LAST=$(ls -d "${DIR}/dd.run"* | tail -n 1)
        local MSG=$(tail -n 1 "${LAST}/dd.compare.out")
        printf "%-30s   %-6s   %-5d   %s\n" "${NAME}" "${STATUS}" "${COUNT}" "${MSG}"
    done | sort -n -r --key 3
}

printf "%-30s   %-6s   %-5s   %s\n" "NAME" "STATUS" "COUNT" "MSG"
echo "--------------------------------------------------------------------------------"
synthese sym
synthese line
