#!/bin/bash

# Computes integral and stores error data
./unitTest.exe 1.1 > cvPlot.dat

# Plots the error as a fucntion of the number of rectangles and outputs the plot to `cvPlot.pdf`
gnuplot cvPlot.gp

# Computes integral with debug functions
#./unitTest_debug.exe 1.1

# runs code with shaman_profiler
../../tools/shaman_profiler/shaman_prof.sh ./unitTest_debug.exe 1.1
