#!/bin/bash

# Arguments en ligne de commande:
# - le répertoire où les résultats doivent être stockés
OUTDIR=$1

# Lancement du code avec Verrou, en stockant les résultats dans ${OUTDIR}
for i in $(seq 3); do
    valgrind --tool=verrou --demangle=no --rounding-mode=random --exclude=libm.ex ./unitTest >${OUTDIR}/res_$i.dat
done

./util/avg-stdev --col=2 --dev-max=1e-6 ${OUTDIR}/res*.dat \
                 2>${OUTDIR}/stdev >${OUTDIR}/res.stat \
    && touch ${OUTDIR}/OK
