#!/bin/bash

VERROU="valgrind --tool=verrou --rounding-mode=random --demangle=no --exclude=libm.ex"
CMD="./unitTest 1.1"

rm -f *.gcda
${CMD} >/dev/null 2>/dev/null
gcov *.cxx
rm -rf gcovStd && mkdir gcovStd
mv *.gcov gcovStd

rm *.gcda
for i in `seq 1 3` ; do
    ${VERROU} ${CMD} >/dev/null 2>/dev/null
    gcov *.cxx
    rm -rf gcovVerrou && mkdir gcovVerrou
    mv *.gcov gcovVerrou
    rm *.gcda
    diff -u gcovStd gcovVerrou || break
done

meld gcovStd gcovVerrou &
