#!/bin/bash

# Réalise l'étude de convergence du calcul d'intégrale
./unitTest 1.1 >cvPlot.dat
VERROU="valgrind --tool=verrou --rounding-mode=random --demangle=no --exclude=libm.ex"
$VERROU ./unitTest 1.1 >cvPlot1.dat
$VERROU ./unitTest 1.1 >cvPlot2.dat
$VERROU ./unitTest 1.1 >cvPlot3.dat

# Calcule le "rapport signal sur bruit" en post-traitement
./util/avg-stdev --col=2 cvPlot*.dat >cvPlot.stat

# Produit une courbe représentant l'erreur en fonction du nombre de rectangles dans "cvPlot.pdf"
gnuplot cvPlot.gp
